### ISSUE TITLE
Including nonexistent blocks has an incorrect error message

### ISSUE THREAD

**Issue by brianhou** [albert12132/templar#30]
When `<include shakespeare.py:nonexistent-block>` is in a file, the error message is `Found multiple blocks with name "build-successors-table" in prob/topics/dictionaries/shakespeare/shakespeare.py`. It should say that `nonexistent-block` doesn't exist.

```
Traceback (most recent call last):
  File "/usr/local/var/pyenv/versions/61a/bin/templar", line 9, in <module>
    load_entry_point('templar==2.1.1', 'console_scripts', 'templar')()
  File "/usr/local/var/pyenv/versions/3.4.4/envs/61a/lib/python3.4/site-packages/templar/cli/templar.py", line 63, in main
    run(flags())
  File "/usr/local/var/pyenv/versions/3.4.4/envs/61a/lib/python3.4/site-packages/templar/cli/templar.py", line 51, in run
    no_write=args.print)
  File "/usr/local/var/pyenv/versions/3.4.4/envs/61a/lib/python3.4/site-packages/templar/api/publish.py", line 58, in publish
    all_block, extracted_variables = linker.link(source)
  File "/usr/local/var/pyenv/versions/3.4.4/envs/61a/lib/python3.4/site-packages/templar/linker.py", line 18, in link
    content.splitlines(), block_map, LinkStack(source_path), source_path)
  File "/usr/local/var/pyenv/versions/3.4.4/envs/61a/lib/python3.4/site-packages/templar/linker.py", line 190, in convert_lines_to_block
    inner_block_name)
  File "/usr/local/var/pyenv/versions/3.4.4/envs/61a/lib/python3.4/site-packages/templar/linker.py", line 203, in convert_lines_to_block
    included_content = process_links(include_match, block_map, link_stack, source_path)
  File "/usr/local/var/pyenv/versions/3.4.4/envs/61a/lib/python3.4/site-packages/templar/linker.py", line 263, in process_links
    link_stack)
  File "/usr/local/var/pyenv/versions/3.4.4/envs/61a/lib/python3.4/site-packages/templar/linker.py", line 301, in retrieve_block_from_map
    convert_lines_to_block(content.splitlines(), block_map, link_stack, filename)
  File "/usr/local/var/pyenv/versions/3.4.4/envs/61a/lib/python3.4/site-packages/templar/linker.py", line 190, in convert_lines_to_block
    inner_block_name)
  File "/usr/local/var/pyenv/versions/3.4.4/envs/61a/lib/python3.4/site-packages/templar/linker.py", line 203, in convert_lines_to_block
    included_content = process_links(include_match, block_map, link_stack, source_path)
  File "/usr/local/var/pyenv/versions/3.4.4/envs/61a/lib/python3.4/site-packages/templar/linker.py", line 263, in process_links
    link_stack)
  File "/usr/local/var/pyenv/versions/3.4.4/envs/61a/lib/python3.4/site-packages/templar/linker.py", line 301, in retrieve_block_from_map
    convert_lines_to_block(content.splitlines(), block_map, link_stack, filename)
  File "/usr/local/var/pyenv/versions/3.4.4/envs/61a/lib/python3.4/site-packages/templar/linker.py", line 190, in convert_lines_to_block
    inner_block_name)
  File "/usr/local/var/pyenv/versions/3.4.4/envs/61a/lib/python3.4/site-packages/templar/linker.py", line 215, in convert_lines_to_block
    block_map.add_block(block)
  File "/usr/local/var/pyenv/versions/3.4.4/envs/61a/lib/python3.4/site-packages/templar/linker.py", line 80, in add_block
    'Found multiple blocks with name "{}" in {}'.format(block.name, block.source_path))
templar.linker.InvalidBlockName: Found multiple blocks with name "build-successors-table" in prob/topics/dictionaries/shakespeare/shakespeare.py
```

**Comment by albert12132** [comment]
I'm not able to reproduce this. Is it possible that you actually did have multiple blocks with name "build-successors-table" in that file?
